root: true
env:
  node: true
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
  - jest
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:jest/recommended
  - prettier
